files:
  - source: "/src/main/resources/io/jenkins/plugins/pipelinegraphview/**/*.properties"
    ignore:
      - "/src/main/resources/io/jenkins/plugins/pipelinegraphview/**/%file_name%_%two_letters_code%.properties"
      - "/src/main/resources/io/jenkins/plugins/pipelinegraphview/**/%file_name%_%locale_with_underscore%.properties"
    translation: "/src/main/resources/io/jenkins/plugins/pipelinegraphview/**/%file_name%_%two_letters_code%.properties"
    escape_quotes: 1
    escape_special_characters: 0

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
