Build\ cancelled=Build cancelled
Build\ paused=Build paused
Build\ resumed=Build resumed
Cancel=Cancel
Configure=Configure
Confirm=Are you sure you want to abort {0}?
Edit\ parameters\ and\ rebuild=Edit parameters and rebuild
Edit\ Pipeline\ and\ replay=Edit Pipeline and replay
Pause=Pause
Pause\ the\ running\ build=Pause the running build
Rerun=Rerun
Rerun\ now=Rerun now
Replay=Replay
Resume=Resume
Resume\ the\ paused\ build=Resume the paused build
Rebuild=Rebuild
Restart\ from\ Stage=Restart from Stage
Restart\ Pipeline\ from\ a\ specific\ Stage=Restart Pipeline from a specific Stage
